#!/bin/bash

CYAN="\033[1;36m"
NC="\033[1;0m"
CRDIR=$(pwd)
MODIR="/sdcard/Magisk-Module/"

build_all()
{
    files=$(ls -d1 */)
    for i in ${files[@]}; do
        cd $i
        shopt -s extglob
        filename=$(echo $i | sed 's:/*$::')
        echo -e "$CYAN[+] Building $filename$NC"
        zip -qr $filename *
        if [ ! -d $MODIR ]; then
            mkdir $MODIR
        fi
        echo "Moving $filename.zip to $MODIR"
        mv $filename.zip $MODIR
        cd $CRDIR
    done
    unset i
    return 0
}

build_selected()
{
    files=$(ls -d1 */)
    select choice in ${files[@]}; do
        cd $choice
        shopt -s extglob
        filename=$(echo $choice | sed 's:/*$::')
        echo -e "$CYAN[+] Building $filename$NC"
        zip -qr $filename *
        if [ ! -d $MODIR ]; then
            mkdir $MODIR
        fi
        echo "Moving $filename.zip to $MODIR"
        mv $filename.zip $MODIR
        cd $CRDIR
    done
    return 0
}
show_help()
{
    echo -e "
Usage: $0 [options]

Options:
         -a, --all, all              : build all
         -s, --selected, selected    : build selected
         -h, --help, help            : show help screen
"
}

case $1 in
    -a|--all|all)
        build_all
        ;;
    -s|--selected|selected)
        build_selected
        ;;
    -h|--help|help|*)
        show_help
        ;;
esac

