#!/bin/bash

CYAN="\033[1;36m"
NC="\033[1;0m"
CRDIR=$(pwd)

update_all()
{
    files=$(ls -d1 */)
    for i in ${files[@]}; do
        cd $i
        shopt -s extglob
        filename=$(echo $i | sed 's:/*$::')
        echo -e "$CYAN[+] Updating $filename$NC"
        git pull
        cd $CRDIR
    done
    unset i
    return 0
}

update_selected()
{
    files=$(ls -d1 */)
    select choice in ${files[@]}; do
        cd $choice
        shopt -s extglob
        filename=$(echo $choice | sed 's:/*$::')
        echo -e "$CYAN[+] Updating $filename$NC"
        git pull
        cd $CRDIR
    done
    return 0
}
show_help()
{
    echo -e "
Usage: $0 [options]

Options:
         -a, --all, all              : update all
         -s, --selected, selected    : update selected
         -h, --help, help            : show help screen
"
}

case $1 in
    -a|--all|all)
        update_all
        ;;
    -s|--selected|selected)
        update_selected
        ;;
    -h|--help|help|*)
        show_help
        ;;
esac

